<a href="https://colab.research.google.com/github/FelipeNunesReis/Analises/blob/main/AnalysisHouses_rent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
aluguel_casa= pd.read_excel('/content/houses_rent.xlsx')

In [ ]:
aluguel_casa.head(5)

,index,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa,rent amount,property tax,fire insurance,total
0,0,Barcelona,240,3,3,4,-,accept,furnished,600,8000,1000,121,9121
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820,122,11,1493
2,2,Barcelona,443,5,5,4,3,accept,furnished,4172,7000,1417,89,12680
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250,150,16,2116
4,4,Barcelona,19,1,1,0,-,not accept,not furnished,0,1200,41,16,1257

In [ ]:
aluguel_casa = aluguel_casa.rename(columns={'parking spaces':'parking_space','rent amount':'rent_amount','property tax':'property_tax','fire insurance':'fire_insurance'})

In [ ]:
aluguel_casa.head()

,index,city,area,rooms,bathroom,parking_space,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
0,0,Barcelona,240,3,3,4,-,accept,furnished,600,8000,1000,121,9121
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820,122,11,1493
2,2,Barcelona,443,5,5,4,3,accept,furnished,4172,7000,1417,89,12680
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250,150,16,2116
4,4,Barcelona,19,1,1,0,-,not accept,not furnished,0,1200,41,16,1257

In [ ]:
aluguel_casa.dtypes

index              int64
city              object
area               int64
rooms              int64
bathroom           int64
parking_space      int64
floor             object
animal            object
furniture         object
hoa               object
rent_amount        int64
property_tax       int64
fire_insurance     int64
total              int64
dtype: object

In [ ]:
aluguel_casa = aluguel_casa.astype({'rent_amount':'float','property_tax':'float','fire_insurance':'float','total':'float'})

In [ ]:
aluguel_casa.dtypes

index               int64
city               object
area                int64
rooms               int64
bathroom            int64
parking_space       int64
floor              object
animal             object
furniture          object
hoa                object
rent_amount       float64
property_tax      float64
fire_insurance    float64
total             float64
dtype: object

In [ ]:
aluguel_casa.head(5)

,index,city,area,rooms,bathroom,parking_space,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
0,0,Barcelona,240,3,3,4,-,accept,furnished,600,8000.0,1000.0,121.0,9121.0
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820.0,122.0,11.0,1493.0
2,2,Barcelona,443,5,5,4,3,accept,furnished,4172,7000.0,1417.0,89.0,12680.0
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250.0,150.0,16.0,2116.0
4,4,Barcelona,19,1,1,0,-,not accept,not furnished,0,1200.0,41.0,16.0,1257.0

In [ ]:
aluguel_casa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6080 entries, 0 to 6079
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           6080 non-null   int64
 1   city            6080 non-null   object
 2   area            6080 non-null   int64
 3   rooms           6080 non-null   int64
 4   bathroom        6080 non-null   int64
 5   parking_space   6080 non-null   int64
 6   floor           6080 non-null   object
 7   animal          6080 non-null   object
 8   furniture       6080 non-null   object
 9   hoa             6080 non-null   object
 10  rent_amount     6080 non-null   float64
 11  property_tax    6080 non-null   float64
 12  fire_insurance  6080 non-null   float64
 13  total           6080 non-null   float64
dtypes: float64(4), int64(5), object(5)
memory usage: 665.1+ KB

In [ ]:
aluguel_casa[['area','rooms','bathroom','parking_space','rent_amount','property_tax','fire_insurance','total']].describe()

,area,rooms,bathroom,parking_space,rent_amount,property_tax,fire_insurance,total
count,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000
mean,151.143914,2.492599,2.341612,1.756250,4395.844408,490.533224,58.204276,6033.194572
std,375.559485,1.129665,1.438860,1.611909,3576.668946,6212.549484,49.313441,8751.347700
min,10.000000,1.000000,1.000000,0.000000,420.000000,0.000000,3.000000,660.000000
25%,58.000000,2.000000,1.000000,1.000000,1800.000000,34.000000,23.000000,2451.500000
50%,100.000000,3.000000,2.000000,1.000000,3111.000000,145.000000,41.000000,4128.500000
75%,200.000000,3.000000,3.000000,2.000000,5952.500000,458.000000,77.000000,8074.000000
max,24606.000000,10.000000,10.000000,12.000000,45000.000000,366300.000000,677.000000,372700.000000

In [ ]:
aluguel_casa= aluguel_casa[(aluguel_casa['total']<=4000)]
aluguel_casa.head()

,index,city,area,rooms,bathroom,parking_space,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820.0,122.0,11.0,1493.0
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250.0,150.0,16.0,2116.0
4,4,Barcelona,19,1,1,0,-,not accept,not furnished,0,1200.0,41.0,16.0,1257.0
5,5,Barcelona,13,1,1,0,2,accept,not furnished,0,2200.0,42.0,28.0,2270.0
7,7,Barcelona,55,2,2,1,2,accept,not furnished,600,1300.0,67.0,17.0,1984.0

In [ ]:
aluguel_casa=aluguel_casa[(aluguel_casa['total']<=4000) & (aluguel_casa['animal']=='accept')]
aluguel_casa.head()

,index,city,area,rooms,bathroom,parking_space,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820.0,122.0,11.0,1493.0
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250.0,150.0,16.0,2116.0
5,5,Barcelona,13,1,1,0,2,accept,not furnished,0,2200.0,42.0,28.0,2270.0
7,7,Barcelona,55,2,2,1,2,accept,not furnished,600,1300.0,67.0,17.0,1984.0
8,8,Barcelona,82,3,1,1,3,accept,furnished,828,2000.0,109.0,26.0,2963.0

In [ ]:
aluguel_casa=aluguel_casa[(aluguel_casa['total']<=4000) & (aluguel_casa['animal']=='accept') & (aluguel_casa['rooms']==2) | (aluguel_casa['rooms']==3)]
aluguel_casa

,index,city,area,rooms,bathroom,parking_space,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820.0,122.0,11.0,1493.0
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250.0,150.0,16.0,2116.0
7,7,Barcelona,55,2,2,1,2,accept,not furnished,600,1300.0,67.0,17.0,1984.0
8,8,Barcelona,82,3,1,1,3,accept,furnished,828,2000.0,109.0,26.0,2963.0
15,15,Porto,56,2,1,1,1,accept,not furnished,345,950.0,11.0,13.0,1319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6058,6058,Barcelona,72,2,1,1,4,accept,not furnished,860,1440.0,0.0,19.0,2319.0
6059,6059,Barcelona,59,2,1,1,10,accept,not furnished,589,1500.0,0.0,20.0,2109.0
6065,6065,Barcelona,133,2,2,1,7,accept,not furnished,813,2713.0,160.0,35.0,3721.0
6075,6075,Barcelona,50,2,1,1,2,accept,not furnished,420,1150.0,0.0,15.0,1585.0
6079,6079,Barcelona,60,2,1,1,4,accept,furnished,489,1900.0,0.0,25.0,2414.0